import React, { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Loader2, AlertCircle, CheckCircle2, Flag } from 'lucide-react';

export default function AutoGeneratedIncidentReview() {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [lookbackDays, setLookbackDays] = useState(7);

  const { data: pendingIncidents, refetch } = useQuery({
    queryKey: ['pendingIncidents'],
    queryFn: async () => {
      const incidents = await base44.entities.Incident.filter({ 
        status: 'pending_review',
        auto_generated: true
      });
      return incidents?.sort((a, b) => new Date(b.incident_date) - new Date(a.incident_date)) || [];
    }
  });

  const handleDetectIncidents = async () => {
    setIsAnalyzing(true);
    try {
      const result = await base44.functions.invoke('detectSessionIncidents', {
        lookback_days: lookbackDays
      });
      refetch();
    } catch (err) {
      alert('Error detecting incidents: ' + err.message);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleConfirmIncident = async (incidentId) => {
    try {
      await base44.entities.Incident.update(incidentId, { status: 'confirmed' });
      refetch();
    } catch (err) {
      alert('Error confirming incident: ' + err.message);
    }
  };

  const handleDismissIncident = async (incidentId) => {
    try {
      await base44.entities.Incident.update(incidentId, { status: 'dismissed' });
      refetch();
    } catch (err) {
      alert('Error dismissing incident: ' + err.message);
    }
  };

  const riskColors = {
    critical: 'bg-red-100 border-red-300 text-red-900',
    high: 'bg-orange-100 border-orange-300 text-orange-900',
    medium: 'bg-yellow-100 border-yellow-300 text-yellow-900',
    low: 'bg-blue-100 border-blue-300 text-blue-900'
  };

  const riskBadgeColors = {
    critical: 'bg-red-600',
    high: 'bg-orange-600',
    medium: 'bg-yellow-600',
    low: 'bg-blue-600'
  };

  const criticalIncidents = pendingIncidents?.filter(i => i.risk_level === 'critical') || [];
  const highIncidents = pendingIncidents?.filter(i => i.risk_level === 'high') || [];

  return (
    <div className="space-y-6">
      {/* Detection Controls */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Detect Incidents</CardTitle>
          <CardDescription>Scan recent sessions for high-risk patterns and concerns</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex gap-2">
            {[7, 14, 30].map(days => (
              <Button
                key={days}
                variant={lookbackDays === days ? 'default' : 'outline'}
                size="sm"
                onClick={() => setLookbackDays(days)}
              >
                Last {days} days
              </Button>
            ))}
          </div>
          <Button
            onClick={handleDetectIncidents}
            disabled={isAnalyzing}
            className="w-full"
          >
            {isAnalyzing ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Scanning...
              </>
            ) : (
              'Scan for Incidents'
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Critical Incidents Alert */}
      {criticalIncidents.length > 0 && (
        <Alert className="border-red-300 bg-red-50">
          <AlertCircle className="h-4 w-4 text-red-600" />
          <AlertDescription className="text-red-700">
            <strong>{criticalIncidents.length} critical incident(s)</strong> require immediate review and action.
          </AlertDescription>
        </Alert>
      )}

      {/* Summary Stats */}
      {pendingIncidents && pendingIncidents.length > 0 && (
        <div className="grid grid-cols-3 gap-4">
          <Card>
            <CardContent className="pt-6 text-center">
              <p className="text-2xl font-bold text-slate-900">{pendingIncidents.length}</p>
              <p className="text-xs text-slate-600">Pending Review</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6 text-center">
              <p className="text-2xl font-bold text-red-600">{criticalIncidents.length}</p>
              <p className="text-xs text-slate-600">Critical</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6 text-center">
              <p className="text-2xl font-bold text-orange-600">{highIncidents.length}</p>
              <p className="text-xs text-slate-600">High Risk</p>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Incidents List */}
      {pendingIncidents && pendingIncidents.length > 0 ? (
        <Tabs defaultValue="all" className="w-full">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="all">All ({pendingIncidents.length})</TabsTrigger>
            <TabsTrigger value="critical">Critical ({criticalIncidents.length})</TabsTrigger>
            <TabsTrigger value="high">High ({highIncidents.length})</TabsTrigger>
          </TabsList>

          {['all', 'critical', 'high'].map(tab => {
            const filtered = tab === 'all' ? pendingIncidents :
                           tab === 'critical' ? criticalIncidents : highIncidents;

            return (
              <TabsContent key={tab} value={tab} className="space-y-3 mt-4">
                {filtered.map(incident => (
                  <Card key={incident.id} className={`border-l-4 ${riskColors[incident.risk_level]}`}>
                    <CardContent className="pt-6 space-y-3">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1">
                            <h4 className="font-semibold text-sm">{incident.description}</h4>
                            <Badge className={riskBadgeColors[incident.risk_level]}>
                              {incident.risk_level}
                            </Badge>
                          </div>
                          <p className="text-xs text-slate-600">
                            {incident.incident_date} • {incident.incident_type}
                          </p>
                        </div>
                        {incident.requires_immediate_attention && (
                          <Flag className="h-4 w-4 text-red-600 flex-shrink-0" />
                        )}
                      </div>

                      {incident.notes && (
                        <div className="text-xs text-slate-700 bg-white/50 rounded p-2">
                          {incident.notes}
                        </div>
                      )}

                      {incident.recommended_action && (
                        <div className="text-xs bg-blue-50 rounded p-2 border border-blue-200">
                          <p className="font-semibold text-blue-900 mb-1">Recommended Action</p>
                          <p className="text-blue-800">{incident.recommended_action}</p>
                        </div>
                      )}

                      <div className="flex gap-2 pt-2 border-t">
                        <Button
                          size="sm"
                          className="flex-1"
                          onClick={() => handleConfirmIncident(incident.id)}
                        >
                          <CheckCircle2 className="h-3 w-3 mr-1" />
                          Confirm & Act
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="flex-1"
                          onClick={() => handleDismissIncident(incident.id)}
                        >
                          Dismiss
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </TabsContent>
            );
          })}
        </Tabs>
      ) : (
        <Card>
          <CardContent className="flex items-center justify-center py-12 text-slate-500">
            <p>No pending incidents</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}