import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

const NDIS_24H_SEVERITIES = ['critical', 'serious_injury', 'safeguarding_concern'];
const MANAGER_EMAIL = Deno.env.get('MANAGER_EMAIL') || 'manager@breakthroughcc.com.au';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    // Allow both scheduled (service role) and manual (admin) invocations
    let isScheduled = false;
    try {
      const body = await req.clone().json();
      isScheduled = body?.scheduled === true;
    } catch {}

    if (!isScheduled) {
      const user = await base44.auth.me();
      if (user?.role !== 'admin') {
        return Response.json({ error: 'Forbidden' }, { status: 403 });
      }
    }

    const client = isScheduled ? base44.asServiceRole : base44;
    const incidents = await client.entities.Incident.filter({});

    const now = new Date();
    const escalations = [];

    for (const incident of incidents) {
      if (!incident.incident_date) continue;
      if (['resolved', 'closed'].includes(incident.status)) continue;

      const incidentTime = new Date(incident.incident_date);
      const hoursElapsed = (now - incidentTime) / (1000 * 60 * 60);
      const daysElapsed = hoursElapsed / 24;

      const needs24hReport = NDIS_24H_SEVERITIES.includes(incident.severity);
      const alerts = [];

      // 24-hour NDIS Commission reporting deadline
      if (needs24hReport) {
        if (hoursElapsed >= 20 && hoursElapsed < 24) {
          alerts.push({ type: '24h_warning', message: `${(24 - hoursElapsed).toFixed(1)}h remaining for NDIS 24-hour report` });
        } else if (hoursElapsed >= 24) {
          alerts.push({ type: '24h_overdue', message: `NDIS 24-hour report OVERDUE by ${(hoursElapsed - 24).toFixed(1)}h` });
        }
      }

      // 5-day detailed report deadline
      if (daysElapsed >= 4 && daysElapsed < 5) {
        alerts.push({ type: '5day_warning', message: `${(5 - daysElapsed).toFixed(1)} days remaining for 5-day report` });
      } else if (daysElapsed >= 5) {
        alerts.push({ type: '5day_overdue', message: `5-day incident report OVERDUE by ${(daysElapsed - 5).toFixed(1)} days` });
      }

      if (alerts.length === 0) continue;

      escalations.push({ incident, alerts });

      // Create Task for each overdue item
      for (const alert of alerts) {
        const isOverdue = alert.type.includes('overdue');
        await client.entities.Task.create({
          title: `[INCIDENT DEADLINE] ${alert.message} — ${incident.client_name || incident.client_id}`,
          category: 'Compliance',
          priority: isOverdue ? 'urgent' : 'high',
          status: 'pending',
          related_entity_type: 'Incident',
          related_entity_id: incident.id,
          due_date: new Date().toISOString().split('T')[0],
          notes: `Auto-generated by incident deadline monitor. Incident date: ${incident.incident_date}. Severity: ${incident.severity}.`,
        });
      }

      // Send escalation email for overdue incidents
      const overdueAlerts = alerts.filter(a => a.type.includes('overdue'));
      if (overdueAlerts.length > 0) {
        const subject = `⚠️ OVERDUE INCIDENT REPORT — ${incident.client_name || 'Client'} (${incident.severity?.replace(/_/g, ' ')})`;
        const body = `
INCIDENT DEADLINE ESCALATION
=============================

Client: ${incident.client_name || incident.client_id}
Severity: ${incident.severity?.replace(/_/g, ' ')}
Incident Date: ${new Date(incident.incident_date).toLocaleString('en-AU', { timeZone: 'Australia/Melbourne' })}
Current Status: ${incident.status}
Location: ${incident.location || 'Not recorded'}

OVERDUE OBLIGATIONS:
${overdueAlerts.map(a => `• ${a.message}`).join('\n')}

REQUIRED ACTION:
Please submit the required NDIS Commission incident report immediately and update the incident status in Breakthrough Manager OS.

Incident ID: ${incident.id}
`.trim();

        await base44.asServiceRole.integrations.Core.SendEmail({
          to: MANAGER_EMAIL,
          subject,
          body,
        });
      }
    }

    return Response.json({
      checked: incidents.length,
      escalations: escalations.length,
      details: escalations.map(e => ({
        incident_id: e.incident.id,
        client: e.incident.client_name,
        severity: e.incident.severity,
        alerts: e.alerts,
      })),
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});