import React from 'react';
import { Alert, AlertDescription } from '@/components/ui/alert';
import AutoGeneratedIncidentReview from '@/components/incidents/AutoGeneratedIncidentReview';
import { AlertCircle } from 'lucide-react';

export default function IncidentDetection() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-slate-900">Incident Detection</h1>
        <p className="text-slate-600 mt-2">AI-detected high-risk events and concerning interactions</p>
      </div>

      {/* Alert */}
      <Alert className="border-red-200 bg-red-50">
        <AlertCircle className="h-4 w-4 text-red-600" />
        <AlertDescription className="text-red-700">
          AI scans SessionContext and SessionSupportLog for risk patterns (unmanaged incidents, rejected risk assessments, intervention failures). Flagged incidents require manager confirmation and action.
        </AlertDescription>
      </Alert>

      {/* Main Component */}
      <AutoGeneratedIncidentReview />
    </div>
  );
}